# -- Main Menu --

[[main]]
  name = "关于"
  pageRef = "posts/authors"
  weight = 5

[[main]]
  name = "博客"
  pageRef = "posts"
  weight = 10

# 运维笔记 父菜单
[[main]]
  name = "Linux"
  parent = "运维"
  pageRef = "categories/linux"
  weight = 21

[[main]]
  name = "Docker"
  parent = "运维"
  pageRef = "docs/docker"
  weight = 22

[[main]]
  name = "Kubernetes"
  parent = "运维"
  pageRef = "docs/kubernetes"
  weight = 23

[[main]]
  name = "CI/CD"
  parent = "运维"
  pageRef = "docs/cicd"
  weight = 24

# 编程
[[main]]
  name = "Go"
  parent = "编程"
  pageRef = "docs/languages/go"
  weight = 31

[[main]]
  name = "Python"
  parent = "编程"
  pageRef = "docs/languages/python"
  weight = 32

[[main]]
  name = "Shell"
  parent = "编程"
  pageRef = "docs/languages/shell"
  weight = 33

# AI 模块
[[main]]
  name = "大模型"
  parent = "AI"
  pageRef = "categories/大模型"
  weight = 51

[[main]]
  name = "AI 工具"
  parent = "AI"
  pageRef = "categories/ai工具"
  weight = 52

[[main]]
  name = "AI 应用"
  parent = "AI"
  pageRef = "categories/ai应用"
  weight = 53

[[main]]
  name = "AIOPS"
  parent = "AI"
  pageRef = "categories/aiops"
  weight = 54

# 资源
[[main]]
  name = "网站导航"
  parent = "资源"
  pageRef = "resources/website"
  weight = 41

[[main]]
  name = "书单"
  parent = "资源"
  pageRef = "books"
  weight = 42

# GitHub 外链（隐藏）
# [[main]]
#   pre = "github"
#   name = "GitHub"
#   url = "https://github.com/socake"
#   weight = 99


# -- Footer Menu --

[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "分类"
  pageRef = "categories"
  weight = 20

[[footer]]
  name = "RSS"
  url = "/index.xml"
  weight = 30

[[footer]]
  name = "赞助"
  pageRef = "sponsor-diy"
  weight = 99
